[package]
name = "excel_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_excel_writer="0.1.4"
calamine = "0.18.0"
clap = "3.1.8"